### ISSUE TITLE
考虑支持QLoRA吗？

### ISSUE THREAD

**Issue by Bit0r** [FlagAlpha/Llama2-Chinese#108]
请问本项目考虑支持[QLoRA](https://arxiv.org/abs/2305.14314)吗？QLoRA比原版LoRA增加了量化机制，使得微调需要的显存更小。

**Comment by Rayrtfr** [comment]
> 请问本项目考虑支持[QLoRA](https://arxiv.org/abs/2305.14314)吗？QLoRA比原版LoRA增加了量化机制，使得微调需要的显存更小。

欢迎提PR给我们，非常感谢

**Comment by ZHangZHengEric** [comment]
目前是支持qlora 的
