### ISSUE TITLE
请问一下微调的时候支持分布式训练吗，在哪里设置呢，目前我这里使用finetune的脚本只有一张卡在跑

### ISSUE THREAD

**Issue by zihao-wang-owo** [FlagAlpha/Llama2-Chinese#117]

**Comment by ZHangZHengEric** [comment]
当然可以，如果使用我们的脚本，只需要设置deepspeed 的启动时的 显卡的id

**Comment by Hades-Z** [comment]
> 

能否详细说一下，用咱们的脚本做并行训练时，如何debug（单步调试）呢？

**Comment by Hades-Z** [comment]
> 当然可以，如果使用我们的脚本，只需要设置deepspeed 的启动时的 显卡的id

能否详细说一下，用咱们的脚本做并行训练时，如何debug（单步调试）呢？
