### ISSUE TITLE
回复的结果是英文

### ISSUE THREAD

**Issue by Maxhyl** [FlagAlpha/Llama2-Chinese#124]
调用本地已下载好的模型文件：
```
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained('/data02/llama2_models/llama-2-7b-chat-hf',device_map='auto',torch_dtype=torch.float16,load_in_8bit=True)
model =model.eval()
tokenizer = AutoTokenizer.from_pretrained('/data02/llama2_models/llama-2-7b-chat-hf',use_fast=False)
tokenizer.pad_token = tokenizer.eos_token
input_ids = tokenizer(['<s>Human: 中文介绍一下中国\n</s><s>Assistant: '], return_tensors="pt",add_special_tokens=False).input_ids.to('cuda')
generate_input = {
    "input_ids":input_ids,
    "max_new_tokens":2048,
    "do_sample":True,
    "top_k":1,
    "top_p":0.6,
    "temperature":0.3,
    "repetition_penalty":1.3,
    "eos_token_id":tokenizer.eos_token_id,
    "bos_token_id":tokenizer.bos_token_id,
    "pad_token_id":tokenizer.pad_token_id
}
generate_ids  = model.generate(**generate_input)
text = tokenizer.decode(generate_ids[0])
print(text)`
```

输出： Assistant: 中国，又称“中华人民共和国”（Zhōngguó, zhè yì “zhōnghuá rén mín gòng héguó”）。 It is a country located in East Asia. China has the largest population of any country in the world and a diverse landscape with many different climates and regions. The capital city of China is Beijing (北京), while Shanghai (上海) is its largest city and financial center. Chinese culture has a long history and has had a significant impact on global art, literature, music, film, and cuisine. Mandarin Chinese is the official language spoken by over one billion people around the world. Do you have anything else you would like to know about China?</s>

**Comment by ZHangZHengEric** [comment]
一定概率下会输出英文，也先确定下载的是我们的中文模型？

**Comment by shenjackyuanjie** [comment]
llama2-7b-chat 当然很大概率输出英语（
