### ISSUE TITLE
LLAMA2 (非chat) Finetune Prompt模板

### ISSUE THREAD

**Issue by qishenghu** [FlagAlpha/Llama2-Chinese#125]
请教一下各位～Readme提供的模板看上去是chat形式的：```"<s>Human: "+问题+"\n</s><s>Assistant: "+答案“```，
如果我想finetune LLAMA2（非chat），模板需要保留 ```Human / Assistant```这种形式吗？
想知道可不可以是这样的：
```<s> Instruction: {Instruction}\n</s><s> Answer: {Answer}</s>```
感谢

**Comment by ZHangZHengEric** [comment]
可以的

**Comment by LKAMING97** [comment]
> 可以的

作为LLM的新手，想了解一下如果跟换这个prompt对模型影响大吗，

**Comment by ZHangZHengEric** [comment]
> > 可以的
> 
> 作为LLM的新手，想了解一下如果跟换这个prompt对模型影响大吗，

没什么影响，只要确定好一种形式，训练和推理都用一种就OK的

**Comment by LKAMING97** [comment]
> > > 可以的
> > 
> > 
> > 作为LLM的新手，想了解一下如果跟换这个prompt对模型影响大吗，
> 
> 没什么影响，只要确定好一种形式，训练和推理都用一种就OK的

就是如果像llama2中文版这种别人一开始微调是定了一种prompt，我后续也要沿用他的是吗

**Comment by ZHangZHengEric** [comment]
最好是，如果使用自己的也可以。沿用的话，学的快，泛化性也比较强。不沿用的话，训练的时候数据要多效果才会好
