### ISSUE TITLE
chat prompt模板没有按照官方给出示例，请问是出于什么考虑？

### ISSUE THREAD

**Issue by beginOfAll** [FlagAlpha/Llama2-Chinese#140]
`<s>Human: 用一句话描述地球为什么是独一无二的。</s><s>Assistant: 因为地球是目前为止唯一已知存在生命的行星。</s>`

官方：
f"{B_INST} {(prompt['content']).strip()} {E_INST} {(answer['content']).strip()} ",

**Comment by LKAMING97** [comment]
同问，想知道原因

**Comment by Rayrtfr** [comment]
> `<s>Human: 用一句话描述地球为什么是独一无二的。</s><s>Assistant: 因为地球是目前为止唯一已知存在生命的行星。</s>`
> 
> 官方： f"{B_INST} {(prompt['content']).strip()} {E_INST} {(answer['content']).strip()} ",

这种方式更方便的使用，没有特殊的考虑

**Comment by ShuFengMuYu** [comment]
> > `<s>Human: 用一句话描述地球为什么是独一无二的。</s><s>Assistant: 因为地球是目前为止唯一已知存在生命的行星。</s>`
> > 官方： f"{B_INST} {(prompt['content']).strip()} {E_INST} {(answer['content']).strip()} ",
> 
> 这种方式更方便的使用，没有特殊的考虑

请问使用这种方式进行调优之后应该使用官方的prompt还是使用这种<s></s>的呢？
