### ISSUE TITLE
这个报错怎么处理

### ISSUE THREAD

**Issue by czw-czw-czw** [FlagAlpha/Llama2-Chinese#144]
bin D:\Anaconda\envs\llama\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
D:\Anaconda\envs\llama\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
Traceback (most recent call last):
  File "D:\Llama2-Chinese\examples\chat_gradio.py", line 86, in <module>
    model = AutoModelForCausalLM.from_pretrained("D:\\Llama2-Chinese\\Llama-2-7b-chat-hf",device_map='auto',torch_dtype=torch.float16,load_in_8bit=True)
  File "D:\Anaconda\envs\llama\lib\site-packages\transformers\models\auto\auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
  File "D:\Anaconda\envs\llama\lib\site-packages\transformers\modeling_utils.py", line 2842, in from_pretrained
    raise ValueError(
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.

**Comment by ZHangZHengEric** [comment]
看报错应该是显存不够吧，可以到微信群进行沟通
