### ISSUE TITLE
有可调用的API吗？

### ISSUE THREAD

**Issue by Hyingerrr** [FlagAlpha/Llama2-Chinese#146]
我已经部署起来了，利用gradio生成了可视化界面。我的需求是用其他服务调用这个部署的llama2，但是没找到llama2的API有哪些，是不是部署llama2之后，没有提供API？

**Comment by Rayrtfr** [comment]
> 我已经部署起来了，利用gradio生成了可视化界面。我的需求是用其他服务调用这个部署的llama2，但是没找到llama2的API有哪些，是不是部署llama2之后，没有提供API？

可以参考这个：https://github.com/FlagAlpha/Llama2-Chinese/blob/main/scripts/api/READMD.md

**Comment by Hyingerrr** [comment]
太赞了
