### ISSUE TITLE
chinese-llama2-7b 输出中文乱码

### ISSUE THREAD

**Issue by shenjunyu57** [FlagAlpha/Llama2-Chinese#149]
为啥使用Chinese-llama2-7b-bit输出时会出现中文乱码

输出：我 转 头 ， � � � � � � � � � 那 里 看 ， 那 里 的 手 电 � � � 了 ， 有 一 个 � � � 音 � � � 到 “ 小 三 � � � ！ ”

**Comment by ZHangZHengEric** [comment]
您使用的是我们的模型吗？如果有更多的信息，才能作出判断

**Comment by shenjunyu57** [comment]
已经解决了，解码的方式出现了错误

**Comment by Rayrtfr** [comment]
> 已经解决了，解码的方式出现了错误

可以试试中文社区刚刚发布的预训练7B模型：
https://huggingface.co/FlagAlpha/Atom-7B

**Comment by v-yunbin** [comment]
> 已经解决了，解码的方式出现了错误

怎么解决的，遇到同样的问题。

**Comment by v-yunbin** [comment]
@Rayrtfr 遇到同样的问题，输出的中文结果是乱码：海外��越、高端车型、结构性发展、品牌向上、海外��越占比增长、产品结构调��理

**Comment by sjy1243143783** [comment]
你的解码方式是怎么样的，解码的时候是一次性输出全部token，还是逐个token生成并打印，如果是逐个token生成并打印出现乱码的原因可能由于编码方式使用的是Byte-Level BPE本身对 byte 进行编码和解码，所以token 不是按照中文或者utf8编码一一对应的

**Comment by sjy1243143783** [comment]
@v-yunbin  你的解码方式是一次性输出所有token，还是逐个token生成并打印，我是逐个token生成并打印会出现乱码，一次性输出所有token不会出现乱码。

**Comment by v-yunbin** [comment]
> ��

我是一次性输出所有token

**Comment by sjy1243143783** [comment]
@v-yunbin  那和我遇到的情况不太一样

**Comment by v-yunbin** [comment]
可能是它的中文词表不全，有些中文字符处理不了。但我使用百川模型是没问题的。
