### ISSUE TITLE
请问你文中提到的 “对齐” 是什么意思？

### ISSUE THREAD

**Issue by edisondeng** [FlagAlpha/Llama2-Chinese#154]
“Meta原始的Llama2 Chat模型对于中文问答的对齐效果一般“， 没理解这里的对齐是什么意思，方便再解释一下吗？谢谢了。

**Comment by fxyfw2** [comment]
> “Meta原始的Llama2 Chat模型对于中文问答的对齐效果一般“， 没理解这里的对齐是什么意思，方便再解释一下吗？谢谢了。

对齐是openai提出的概念，openai表示gpt4以后的产品的重心，是打造人类意图对齐团队。从此这个词就暴热了，到处都在跟风说对齐。各人都有不同理解，见仁见智吧，至于它的原始准确含义，恐怕只有等gpt5出来那一天。搞不好到时全世界会来句“我们猜错了”也说不定【抠鼻】

**Comment by ZHangZHengEric** [comment]
对齐，我理解是就通过微调模型，通过我们的输入，召回我们期望的输出。减少输出的噪音
