### ISSUE TITLE
推理缓慢

### ISSUE THREAD

**Issue by luanshaotong** [FlagAlpha/Llama2-Chinese#16]
P40显卡
我使用https://github.com/facebookresearch/llama部署原版7b-chat模型时，（下载checklist.chk  consolidated.00.pth  params.json三个文件）推理速度非常快，大概1秒5单词左右，为什么用本项目推理中文一秒一个字？

**Comment by Daniel-1997** [comment]
我也有类似疑问，在700多条数据上测试推理，看时间要跑8.5h

**Comment by mougua** [comment]
同问

**Comment by Rayrtfr** [comment]
我们正在整理推理加速的方法，预计提示4～5倍。后续会放到仓库里面。

**Comment by QJShan** [comment]
> https://github.com/facebookresearch/llama

你好，请问你下载完成文件后，有将.pt文件转换成.bin文件吗，直接使用from_pretrain好像不行。

**Comment by Rayrtfr** [comment]
推理的加速方法已经更新了，欢迎使用👏
https://github.com/FlagAlpha/Llama2-Chinese/blob/main/docs/inference_speed_guide.md
