### ISSUE TITLE
Ollama 支援 llama2-chinese

### ISSUE THREAD

**Issue by mchiang0610** [FlagAlpha/Llama2-Chinese#160]
打扰了，有人有问Ollama 有没有支援llama2-chinese. 现在有了。 可以直接在Mac, Windows, Linux 上运行

Ollama 开源: https://github.com/jmorganca/ollama 

---- 

https://ollama.ai/library/llama2-chinese 

API: 
```
  curl -X POST http://localhost:11434/api/generate -d '{
    "model": "llama2-chinese:7b-chat-q4_0",
    "prompt":"为什么天空是蓝色的"
   }'
```
CLI: 

`ollama run llama2-chinese:7b-chat-q4_0` 

`ollama run llama2-chinese:13b-chat-q4_0`

**Comment by ZHangZHengEric** [comment]
感谢，也可以给我们提交issue，我们一并合并起来
