### ISSUE TITLE
 AttributeError: 'DummyOptim' object has no attribute 'step'

### ISSUE THREAD

**Issue by weikeduo1** [FlagAlpha/Llama2-Chinese#163]
没有对代码进行任何修改，运行train/sft/finetune.sh报如上错误

**Comment by weikeduo1** [comment]
注释后还会碰到AttributeError: 'DummyScheduler' object has no attribute 'get_last_lr'
AttributeError: 'DummyScheduler' object has no attribute 'step'

**Comment by ZHangZHengEric** [comment]
没有遇到过相关问题，最好粘贴出全部的log 信息

**Comment by xiaomingtx6** [comment]
> 注释后还会碰到AttributeError: 'DummyScheduler' object has no attribute 'get_last_lr' AttributeError: 'DummyScheduler' object has no attribute 'step'
请问您解决这个问题了吗
