### ISSUE TITLE
could you release the evaluation of atom-7b on c-eval?

### ISSUE THREAD

**Issue by chengmengli06** [FlagAlpha/Llama2-Chinese#165]
could you release the evaluation of atom-7b on c-eval?

**Comment by ZHangZHengEric** [comment]
atom-7b 当前是还在训练中的版本，可关注（https://llama.family/），目前没有计划进行测试

**Comment by chengmengli06** [comment]
we have test the atom-7b model, the performance is significantly worse than chatglm2-6b, c-eval is 28.9; I think your guys should release atom-13b model. The atom-7b is not ready yet.
