### ISSUE TITLE
全参数微调时，报没有 target_modules 变量

### ISSUE THREAD

**Issue by mzgcz** [FlagAlpha/Llama2-Chinese#169]
https://github.com/FlagAlpha/Llama2-Chinese/blob/80ab0108127bd83e03f10613d2d15fa869c80285/train/sft/finetune_clm.py#L156C1-L157C65

**Comment by metacarbon** [comment]
我直接注释掉了，也是可以跑起来的

**Comment by qiangtang2017** [comment]
注释了是可以跑

**Comment by huxiaosheng123** [comment]
这个问题 可以参考这：https://github.com/huxiaosheng123/open-llama2
