### ISSUE TITLE
请问这个模型到底是自己从头训练，还是基于LLAMA 2微调？

### ISSUE THREAD

**Issue by fishfree** [FlagAlpha/Llama2-Chinese#170]
README.md里写着：基于大规模中文数据，从预训练开始对Llama2模型进行中文能力的持续迭代升级
但又说：发布基于Llama2进行中文预训练的开源大模型[Atom-7B](https://huggingface.co/FlagAlpha/Atom-7B)，并将持续更新，详情参考[社区公众号文章](https://mp.weixin.qq.com/s/Bdx0JTVh1kgPn5ydYxIkEw)！

到底该怎么理解啊？如果是前者，该看哪个文件来学习从头训练的思路？

先谢过了！

**Comment by ZHangZHengEric** [comment]
模型是在llama2 的参数的基础上，继续进行中文预训练。应该是一个意思吧。说的比较通透

**Comment by zjuAJW** [comment]
请问，Atom-7B是全量参数预训练，而Llama2-Chinese-Chat系列是使用Lora做的sft微调吗？

**Comment by huxiaosheng123** [comment]
重头训练可以参考这个：https://github.com/huxiaosheng123/open-llama2

**Comment by Rayrtfr** [comment]
> README.md里写着：基于大规模中文数据，从预训练开始对Llama2模型进行中文能力的持续迭代升级 但又说：发布基于Llama2进行中文预训练的开源大模型[Atom-7B](https://huggingface.co/FlagAlpha/Atom-7B)，并将持续更新，详情参考[社区公众号文章](https://mp.weixin.qq.com/s/Bdx0JTVh1kgPn5ydYxIkEw)！
> 
> 到底该怎么理解啊？如果是前者，该看哪个文件来学习从头训练的思路？
> 
> 先谢过了！

Atom-7B 基于大规模中文数据，从预训练开始对Llama2模型进行预训练。
预训练代码：https://github.com/FlagAlpha/Llama2-Chinese/blob/main/train/pretrain/pretrain_clm.py
