### ISSUE TITLE
这个项目很优秀。但它和深圳大学的“伶荔”相比，有什么区别呢?

### ISSUE THREAD

**Issue by DirtyKnightForVi** [FlagAlpha/Llama2-Chinese#171]
如题。
https://github.com/CVI-SZU/Linly
https://huggingface.co/Linly-AI/Chinese-LLaMA-2-7B-hf

**Comment by Rayrtfr** [comment]
> 使用者的角度来看，atom 7b比linly13b好，也可能是提示词之类的问题。这个项目的另外一个模型只微调的那个，输出质量不高，建议直接尝试atom。

是的，Atom-7B的模型效果已经不错了，还在继续训练中。
