### ISSUE TITLE
ceval上榜模型的参数有放出来吗？

### ISSUE THREAD

**Issue by hotbaby** [FlagAlpha/Llama2-Chinese#181]

**Comment by hotbaby** [comment]
huggingface上模型Tokenizer词表的大小还是32000呢，看到README上介绍说，有进行扩词表优化？

**Comment by hotbaby** [comment]
> huggingface上模型Tokenizer词表的大小还是32000呢，看到README上介绍说，有进行扩词表优化？

请问，是开源7B的模型，13B的模型没有开源，是这样吗？

**Comment by Rayrtfr** [comment]
> > huggingface上模型Tokenizer词表的大小还是32000呢，看到README上介绍说，有进行扩词表优化？
> 
> 请问，是开源了7B的模型，13B的模型没有开源，是这样吗？

目前13B还没开源
