### ISSUE TITLE
训练数据加和没加<s></s>有什么影响呢？

### ISSUE THREAD

**Issue by cheney369** [FlagAlpha/Llama2-Chinese#184]
加<s></s>是为了更好的区分句子吗？
如果用新数据在仓库的模型上微调，是不是也需要格式一致才行？
如果数据格式不一致进入训练，输出的时候是不是也会自动带<s></s>标记？

**Comment by ZHangZHengEric** [comment]
其实影响不大，主要是为了生成的时候，有停止的和开始，区分比较明显。模型也能学习到语义发生了切换
