### ISSUE TITLE
ERROR: Invalid requirement: 'torch torchvision torchaudio' (from line 13 of requirements.txt)

### ISSUE THREAD

**Issue by yangjianchun** [FlagAlpha/Llama2-Chinese#19]
执行  pip install -r requirements.txt 报 ERROR: Invalid requirement: 'torch torchvision torchaudio' (from line 13 of requirements.txt) 咋回事？

**Comment by liuhao-0666** [comment]
![image](https://github.com/FlagAlpha/Llama2-Chinese/assets/103105038/24ebe573-22e7-4171-8323-1a1ba29ba256)

遇到同样问题+1

**Comment by Rayrtfr** [comment]
问题，我们已经修复了，感谢
