### ISSUE TITLE
有没有70B的训练计划？

### ISSUE THREAD

**Issue by kanzhang-jason** [FlagAlpha/Llama2-Chinese#190]
试用了7B和13B的版本，在实际的应用上，感觉模型能力上还有一些欠缺。有70B的训练计划吗？

**Comment by huxiaosheng123** [comment]
可以参考这个：https://github.com/huxiaosheng123/open-llama2

**Comment by Rayrtfr** [comment]
> 试用了7B和13B的版本，在实际的应用上，感觉模型能力上还有一些欠缺。有70B的训练计划吗？

正在排期中

**Comment by ycjcl868** [comment]
蹲个 FlagAlpha/Llama2-Chinese-70b-Chat
