### ISSUE TITLE
官网上提交的数据训练完要如何下载

### ISSUE THREAD

**Issue by yongzheJIN** [FlagAlpha/Llama2-Chinese#191]
![image](https://github.com/FlagAlpha/Llama2-Chinese/assets/52804241/8b2ac60f-65bb-4fa2-b3ba-8002100b6b14)
因为我也不需要登录便可以提交数据进行训练，所以我想知道后续如何下载到微调后的模型。

**Comment by ZHangZHengEric** [comment]
模型是开源的，都可以下载，这些数据目前还没有加到批次训练中，应该近期会加进去。
