### ISSUE TITLE
能否提供sha256

### ISSUE THREAD

**Issue by AnxietyYoungPoet** [FlagAlpha/Llama2-Chinese#20]
下载了国内地址的7b模型后, 用最新的llama.cpp convert会出错, 怀疑是下载过程中出错了, 能否提供下各个模型的sha256 方便对比

**Comment by Rayrtfr** [comment]
<img width="1070" alt="image" src="https://github.com/FlagAlpha/Llama2-Chinese/assets/139932418/818b49c7-929b-448d-a4ea-26d50ec08d49">
已经有了哈，这个文件哈
