### ISSUE TITLE
LLaMA2模型求助

### ISSUE THREAD

**Issue by JiwenJ** [FlagAlpha/Llama2-Chinese#207]
你好，请问一下meta llama2模型有没有百度网盘链接，谢谢作者和大家

**Comment by Banana-Basilisk** [comment]
表示我也想要，迅雷的网盘下载不了

**Comment by JiwenJ** [comment]
@Banana-Basilisk 现在应该都好搞，你还没有么

**Comment by Banana-Basilisk** [comment]
昨天刚开始接触llama，想玩玩模型训练这一块，现在已经有了哈

> @Banana-Basilisk 现在应该都好搞，你还没有么
