### ISSUE TITLE
OSError: No such device (os error 19)

### ISSUE THREAD

**Issue by yajunDai** [FlagAlpha/Llama2-Chinese#21]
```
from transformers import AutoTokenizer, AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained('meta-llama/Llama-2-7b-chat-hf',device_map='auto',torch_dtype=torch.float16,load_in_8bit=True)
model =model.eval()
tokenizer = AutoTokenizer.from_pretrained('meta-llama/Llama-2-7b-chat-hf',use_fast=False)
tokenizer.pad_token = tokenizer.eos_token
input_ids = tokenizer( [' \<s\>Human: 介绍一下中国\n</s><s>Assistant: '], return_tensors="pt",add_special_tokens=False).input_ids.to('cuda')        
generate_input = {
    "input_ids":input_ids,
    "max_new_tokens":512,
    "do_sample":True,
    "top_k":50,
    "top_p":0.95,
    "temperature":0.3,
    "repetition_penalty":1.3,
    "eos_token_id":tokenizer.eos_token_id,
    "bos_token_id":tokenizer.bos_token_id,
    "pad_token_id":tokenizer.pad_token_id
}
generate_ids  = model.generate(**generate_input)
text = tokenizer.decode(generate_ids[0])
print(text)

```

按照案例执行，把“meta-llama/Llama-2-7b-chat-hf”改成自己的目录，会报错
model │
│ ing_utils.py:447 in load_state_dict                                                             │
│                                                                                                 │
│    444 │   """                                                                                  │
│    445 │   if checkpoint_file.endswith(".safetensors") and is_safetensors_available():          │
│    446 │   │   # Check format of the archive                                                    │
│ ❱  447 │   │   with safe_open(checkpoint_file, framework="pt") as f:                            │
│    448 │   │   │   metadata = f.metadata()                                                      │
│    449 │   │   if metadata.get("format") not in ["pt", "tf", "flax"]:                           │
│    450 │   │   │   raise OSError(                                                               │
╰─────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: No such device (os error 19)

 请问是为啥？

**Comment by Rayrtfr** [comment]
有更多的报错日志吗

**Comment by lucaschang17** [comment]
同问，解决了吗？
