### ISSUE TITLE
CodeLlama-34b官网版本 网盘链接不存在

### ISSUE THREAD

**Issue by gcclua** [FlagAlpha/Llama2-Chinese#210]
CodeLlama-34b官网版本：https://pan.baidu.com/s/10d9rL5QUNSieXrTtY_Jd4A?pwd=7jev

您好，能否重新分享一下，谢谢

**Comment by Rayrtfr** [comment]
> CodeLlama-34b官网版本：https://pan.baidu.com/s/10d9rL5QUNSieXrTtY_Jd4A?pwd=7jev
> 
> 您好，能否重新分享一下，谢谢

已经更新
