### ISSUE TITLE
请问为什么我部署的LLaMa2-chinese-13b-chat的输出结果和您这边在线提供的LLama-family上差距很大？

### ISSUE THREAD

**Issue by huangjianzuishuai** [FlagAlpha/Llama2-Chinese#29]

**Comment by Rayrtfr** [comment]
您好，llama.family上是最新的参数，我们一直在持续优化，最新的参数之后也会更新到Hugging Face，欢迎👏您持续跟进社区的进展。

**Comment by coddderX** [comment]
+10000086. 请问作者，Hugging Face上模型啥时候更新啊？我看时间还是1个月之前的，可否将最新的模型更新上去嘞？我在family上测试效果感觉还行，本地部署太拉跨了
