### ISSUE TITLE
模型效果与chatglm2对比如何？

### ISSUE THREAD

**Issue by ZSitong** [FlagAlpha/Llama2-Chinese#30]
如题，谢谢！

**Comment by Rayrtfr** [comment]
Llama2-Chinese在对中文进行更新训练，目前需要等训练完成之后，有新的版本评测数据哈

**Comment by futureisatyourhand** [comment]
> Llama2-Chinese在对中文进行更新训练，目前需要等训练完成之后，有新的版本评测数据哈

你好，评测结果呢？
