### ISSUE TITLE
预训练

### ISSUE THREAD

**Issue by ZTurboX** [FlagAlpha/Llama2-Chinese#31]
想用自己领域全量预训练需要怎么做

**Comment by ZHangZHengEric** [comment]
可以参考hf 上的train clm

**Comment by sun1092469590** [comment]
> 可以参考hf 上的train clm

@ZHangZHengEric   啥意思？方便发一下网址吗？

**Comment by huxiaosheng123** [comment]
参考这个：https://github.com/huxiaosheng123/open-llama2
