### ISSUE TITLE
有做中文词表扩充吗

### ISSUE THREAD

**Issue by louieyliu** [FlagAlpha/Llama2-Chinese#34]

**Comment by QJShan** [comment]
同问！
vocab_size只有32000 是怎么做到同事囊括多种语言的呢。
我看GLM的vocab_size都有超过10W
原本llama的语料库中大部分都是英文，在做中文微调时，是怎样对样编码的，如果不做词表扩充，原始llama的词表里面就囊括的所有的中文吗

**Comment by ZHangZHengEric** [comment]
> 同问！ vocab_size只有32000 是怎么做到同事囊括多种语言的呢。 我看GLM的vocab_size都有超过10W 原本llama的语料库中大部分都是英文，在做中文微调时，是怎样对样编码的，如果不做词表扩充，原始llama的词表里面就囊括的所有的中文吗

建议可以了解一下 llama tokenizer 的原理，通过将所有数据拆分回退到字节以分解未知的utf8字符。
