### ISSUE TITLE
缺少config.json文件

### ISSUE THREAD

**Issue by pkuhsczy** [FlagAlpha/Llama2-Chinese#4]
does not appear to have a file named config.json.好像是缺少config.json文件。

**Comment by Jin2022** [comment]
你下载的是Llama-2-7b-chat-hf   hf后缀的版本吗还是这个https://huggingface.co/meta-llama/Llama-2-7b-chat

**Comment by pkuhsczy** [comment]
> 你下载的是Llama-2-7b-chat-hf hf后缀的版本吗还是这个https://huggingface.co/meta-llama/Llama-2-7b-chat

我是从迅雷上下载的。

**Comment by Jin2022** [comment]
> > 你下载的是Llama-2-7b-chat-hf hf后缀的版本吗还是这个https://huggingface.co/meta-llama/Llama-2-7b-chat
> 
> 我是从迅雷上下载的。

一群里面发的那个吗，他那是官方原版，得下官方转成Hugging Face Transformers格式的模型（[Llama-2-7b-chat-hf](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf) ）

**Comment by pkuhsczy** [comment]
> > > 你下载的是Llama-2-7b-chat-hf hf后缀的版本吗还是这个https://huggingface.co/meta-llama/Llama-2-7b-chat
> > 
> > 
> > 我是从迅雷上下载的。
> 
> 一群里面发的那个吗，他那是官方原版，得下官方转成Hugging Face Transformers格式的模型（[Llama-2-7b-chat-hf](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf) ）

好的，谢谢。据说这个config.json可以用hugging face上别的LLAMA项目的。

**Comment by QJShan** [comment]
> > > 你下载的是Llama-2-7b-chat-hf hf后缀的版本吗还是这个https://huggingface.co/meta-llama/Llama-2-7b-chat
> > 
> > 
> > 我是从迅雷上下载的。
> 
> 一群里面发的那个吗，他那是官方原版，得下官方转成Hugging Face Transformers格式的模型（[Llama-2-7b-chat-hf](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf) ）

我通过填写申请后 使用库中的download.sh下载，里面的选项没有-hf的模型

**Comment by Jin2022** [comment]
> > > > 你下载的是Llama-2-7b-chat-hf hf后缀的版本吗还是这个https://huggingface.co/meta-llama/Llama-2-7b-chat
> > > 
> > > 
> > > 我是从迅雷上下载的。
> > 
> > 
> > 一群里面发的那个吗，他那是官方原版，得下官方转成Hugging Face Transformers格式的模型（[Llama-2-7b-chat-hf](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf) ）
> 
> 我通过填写申请后 使用库中的download.sh下载，里面的选项没有-hf的模型

我是直接https://huggingface.co/meta-llama 官方里面找的，项目的readme文档各种模型下载也是指向那边，不过好像需要用hf的账号授权申请成功后才能看到

**Comment by Rayrtfr** [comment]
国内的迅雷下载里面已经更新了这个文件。
