### ISSUE TITLE
请问怎么将模型与langchain-ChatGLM整合

### ISSUE THREAD

**Issue by string-new** [FlagAlpha/Llama2-Chinese#41]
请问怎么将代码放进langchain-ChatGLM里面呢，配置到model_config.py文件里面启动，目前是不兼容的

**Comment by Rayrtfr** [comment]
> 请问怎么将代码放进langchain-ChatGLM里面呢，配置到model_config.py文件里面启动，目前是不兼容的

可以参考这个代码：https://github.com/FlagAlpha/Llama2-Chinese/blob/main/examples/llama2_for_langchain.py
