### ISSUE TITLE
cuda 11.7 RuntimeError: Error building extension 'cpu_adam'

### ISSUE THREAD

**Issue by ymmbb8882ymmbb** [FlagAlpha/Llama2-Chinese#42]
cuda 11.7 RuntimeError: Error building extension 'cpu_adam' 求解

**Comment by Rayrtfr** [comment]
有更详细的信息吗

**Comment by ymmbb8882ymmbb** [comment]
> 有更详细的信息吗

解决了，是因为gcc版本比较低

**Comment by xf4fresh** [comment]
> > 有更详细的信息吗
> 
> 解决了，是因为gcc版本比较低

请问你目前把GCC升级到了拿个版本呢？

**Comment by xf4fresh** [comment]
> > > 有更详细的信息吗
> > 
> > 
> > 解决了，是因为gcc版本比较低
> 
> 请问你目前把GCC升级到了拿个版本呢？

更新下，尝试5.4.0版本仍旧报错，又尝试7.2.0之后解决
