### ISSUE TITLE
开源的13B模型和网站上体验的demo感觉完全不一样

### ISSUE THREAD

**Issue by GXYM** [FlagAlpha/Llama2-Chinese#45]
https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat 下载了这个模型，在本地测试了一下他的写诗能力，发现和在线网站上的demo （[在线体验：llama.family](https://llama.family/)）完全不一样，请问是什么原因。
本地：
<img width="610" alt="企业微信截图_eda760c3-8724-4f30-a936-92cdee128f24" src="https://github.com/FlagAlpha/Llama2-Chinese/assets/33718991/4b6b911d-c873-4541-9af6-ef9f4d826253">

在线：
<img width="752" alt="企业微信截图_0084ff19-ad80-420b-be7f-54e5f712a806" src="https://github.com/FlagAlpha/Llama2-Chinese/assets/33718991/c2249591-a565-4a67-8bff-d033acf54a90">

**Comment by Rayrtfr** [comment]
在线的版本我们一直在更新，训练完成之后回开放一个版本。请关注我们的更新哈

**Comment by fingerx** [comment]
@Rayrtfr  有具体的roadmap 吗？谢谢

**Comment by Rayrtfr** [comment]
> @Rayrtfr 有具体的roadmap 吗？谢谢

这个还没，欢迎关注咱们的github更新或者加入咱们的微信群
