### ISSUE TITLE
感谢开发者开源，想问一下 huggingface 上两个模型 https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat, https://huggingface.co/FlagAlpha/Llama2-Chinese-7b-Chat  finetune 使用的中文数据集是哪些呢？

### ISSUE THREAD

**Issue by jijeng** [FlagAlpha/Llama2-Chinese#46]
感谢开发者开源，想问一下 huggingface 上两个模型 https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat, https://huggingface.co/FlagAlpha/Llama2-Chinese-7b-Chat  finetune 使用的中文数据集是哪些呢？

**Comment by Rayrtfr** [comment]
> 感谢开发者开源，想问一下 huggingface 上两个模型 https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat, https://huggingface.co/FlagAlpha/Llama2-Chinese-7b-Chat finetune 使用的中文数据集是哪些呢？

微调的SFT数据是社区之前积累的数据
