### ISSUE TITLE
数学问题，胡说八道。

### ISSUE THREAD

**Issue by yunOxO** [FlagAlpha/Llama2-Chinese#53]
![llama-test](https://github.com/FlagAlpha/Llama2-Chinese/assets/132147295/f3d4c594-575c-4e22-8939-59affcb0b9c4)

除了胡说八道外，为什么输入的10,007，输出却变成了10,0007呢？

**Comment by wudijimao** [comment]
这么大的模型可能不能指望有多强的推理能力，作为知识库问答机器人可能可行

**Comment by Rayrtfr** [comment]
模型我们还在持续迭代，后续会进行优化，欢迎持续关注社区发展。
