### ISSUE TITLE
练了个不错的中文llama2 13b chat模型

### ISSUE THREAD

**Issue by CrazyBoyM** [FlagAlpha/Llama2-Chinese#6]
[llama2-13b-Chinese-chat](https://huggingface.co/shareAI/llama2-13b-Chinese-chat)

昨天练的，体验对话效果不错，方便的话可以记录一下。

**Comment by mymusise** [comment]
蹲一个benchmark结果

**Comment by Rayrtfr** [comment]
最近2天，会更新llama2 中文SFT模型

**Comment by CrazyBoyM** [comment]
> 最近2天，会更新llama2 中文SFT模型

增量训练的base模型么

**Comment by lslzl3000** [comment]
大概多少数据量，训练一次成本大概多少
