### ISSUE TITLE
预训练的代码会开源吗

### ISSUE THREAD

**Issue by aaronliu7** [FlagAlpha/Llama2-Chinese#62]
增量训练的也行，期待能早日上线，跑一个自己的base model

**Comment by Rayrtfr** [comment]
> 增量训练的也行，期待能早日上线，跑一个自己的base model

https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py
可以参考这个哈

**Comment by huxiaosheng123** [comment]
参考：https://github.com/huxiaosheng123/open-llama2
