### ISSUE TITLE
构建docker容器最后一步安装pip依赖时报错`No such file or directory: '/usr/local/cuda/bin/nvcc'`

### ISSUE THREAD

**Issue by amazingfate** [FlagAlpha/Llama2-Chinese#65]
```
Building wheels for collected packages: auto-gptq, peft, ffmpy
  Building wheel for auto-gptq (setup.py): started
  Building wheel for auto-gptq (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      appending conda cuda include dir /usr/local/lib/python3.10/site-packages/nvidia/cuda_runtime/include
      running bdist_wheel
      /usr/local/lib/python3.10/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/auto_gptq
      copying auto_gptq/__init__.py -> build/lib.linux-x86_64-cpython-310/auto_gptq
      creating build/lib.linux-x86_64-cpython-310/auto_gptq/eval_tasks
      running build_ext
      error: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc'
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for auto-gptq
```
我在一个没有nvidia cuda环境的机器上构建，不过应该不影响，因为docker build阶段是没有把本地目录映射到容器里的

**Comment by Rayrtfr** [comment]
> ```
> Building wheels for collected packages: auto-gptq, peft, ffmpy
>   Building wheel for auto-gptq (setup.py): started
>   Building wheel for auto-gptq (setup.py): finished with status 'error'
>   error: subprocess-exited-with-error
> 
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [67 lines of output]
>       No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
>       appending conda cuda include dir /usr/local/lib/python3.10/site-packages/nvidia/cuda_runtime/include
>       running bdist_wheel
>       /usr/local/lib/python3.10/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
>         warnings.warn(msg.format('we could not find ninja.'))
>       running build
>       running build_py
>       creating build
>       creating build/lib.linux-x86_64-cpython-310
>       creating build/lib.linux-x86_64-cpython-310/auto_gptq
>       copying auto_gptq/__init__.py -> build/lib.linux-x86_64-cpython-310/auto_gptq
>       creating build/lib.linux-x86_64-cpython-310/auto_gptq/eval_tasks
>       running build_ext
>       error: [Errno 2] No such file or directory: '/usr/local/cuda/bin/nvcc'
>       [end of output]
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for auto-gptq
> ```
> 
> 我在一个没有nvidia cuda环境的机器上构建，不过应该不影响，因为docker build阶段是没有把本地目录映射到容器里的

推荐直接使用Nvidia官方的镜像：nvcr.io/nvidia/pytorch:23.07-py3
