### ISSUE TITLE
微调完以后怎么调用呢?

### ISSUE THREAD

**Issue by ymmbb8882ymmbb** [FlagAlpha/Llama2-Chinese#69]

**Comment by wrenchonline** [comment]
可以查看这个
[微调代码](https://github.com/FlagAlpha/Llama2-Chinese/pull/1/commits/05ff88621403fcaed01dfcce0a6798d0f755420e)

**Comment by huangzsdy** [comment]
同问，用自己的数据微调后怎么调用呢？是否可以转成ollama本地使用的模型格式，怎么转
