### ISSUE TITLE
webui怎么监听地址0.0.0.0？没有找到对应的参数配置

### ISSUE THREAD

**Issue by fengmingxing** [FlagAlpha/Llama2-Chinese#7]
启动命令：python chat_gradio.py --model_name_or_path /root/llama2 
监听地址是
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by fengmingxing** [comment]
尝试修改下chat_gradios的配置。https://github.com/gradio-app/gradio/blob/74d9080fcd60c5ff845c2836b6159762f0f6b526/gradio/blocks.py#L1248

**Comment by ToviHe** [comment]
好像直接设置 server_name = “0.0.0.0” ，server_port = "xxx" 就行了
