### ISSUE TITLE
执行docker发布命令出错！

### ISSUE THREAD

**Issue by Jin-Huiming** [FlagAlpha/Llama2-Chinese#77]
sudo docker build -f docker/Dockerfile  -t FlagAlpha/llama2-chinese-7b:gradio .
ERROR: failed to solve: invalid reference format: repository name must be lowercase

**Comment by zhubao315** [comment]
FlagAlpha 改成小写，或是去掉就行了

**Comment by Rayrtfr** [comment]
> FlagAlpha 改成小写，或是去掉就行了

已经修复
