### ISSUE TITLE
可以出一个教程，在阿里云机器学习PAI 上面直接部署 Llama2-Chinese-7b-Chat 模型吗？

### ISSUE THREAD

**Issue by dividez** [FlagAlpha/Llama2-Chinese#85]
可以出一个教程，在阿里云机器学习PAI 上面直接部署 Llama2-Chinese-7b-Chat 模型吗？

**Comment by Rayrtfr** [comment]
收到，我们会后续考虑一，可以关注一下公众号:  “Llama中文社区”。里面有使用的其它相关教程。
