### ISSUE TITLE
模型调用示例代码prompt格式不对

### ISSUE THREAD

**Issue by lvitol** [FlagAlpha/Llama2-Chinese#9]
参考 https://github.com/facebookresearch/llama/blob/main/llama/generation.py
https://huggingface.co/spaces/huggingface-projects/llama-2-13b-chat/blob/main/model.py

**Comment by Rayrtfr** [comment]
https://github.com/FlagAlpha/Llama2-Chinese/blob/main/examples/chat_gradio.py
这个prompt针对的https://huggingface.co/FlagAlpha 下的中文微调版本。和社区的prompt格式是不同的哈
