### ISSUE TITLE
最大的输出长度只有2048吗

### ISSUE THREAD

**Issue by zihao-wang-owo** [FlagAlpha/Llama2-Chinese#91]
最大的输出长度只有2048吗，这个长度是prompt+output 一起的长度吗，由于我的prompt很长，而且生成的文本有很多的空格，所以无法满足生成的需求，请问有什么办法可以解决吗

**Comment by ZHangZHengEric** [comment]
最大的长度是4096吧，可以看一下配置，4096 对显存的需求就比较大了
