### ISSUE TITLE
Llama2-Chinese-13b-Chat  使用vllm 测试在A10上出现CUDA out of memory , 官方13b-chat 可以运行

### ISSUE THREAD

**Issue by stevensu1977** [FlagAlpha/Llama2-Chinese#94]
A10 ,  测试了meta 官方的llama2-13b-chat 加载正常，但是加载Llama2-Chinese-13b-Chat 出现CUDA out of memory 
from vllm import LLM, SamplingParams
prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
llm = LLM(model="./Llama2-Chinese-13b-Chat")
 outputs = llm.generate(prompts, sampling_params)

#Print the outputs.
 for output in outputs:
     prompt = output.prompt
     generated_text = output.outputs[0].text
     print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

**Comment by Rayrtfr** [comment]
模型参数是一样的，不太应该。是不是您显存当时被其他任务占用呢

**Comment by stevensu1977** [comment]
请忽略，找到原因了，huggingface 推理代码带上了load_in_8bit=True, 而vllm没有，所以HF的可以， 另外这个模型很棒!
